services:
  pypiserver-authenticated:
    image: pypiserver/pypiserver:unstable
    restart: unless-stopped
    environment:
    # Set the maximum file upload size to 100MB, same as PyPI server
    # https://github.com/pypiserver/pypiserver/issues/630
      PYPISERVER_BOTTLE_MEMFILE_MAX_OVERRIDE_BYTES: 104857600
    volumes:
      - type: bind
        source: ./local-pypi/packages
        target: /data/packages
      - type: bind
        source: ./local-pypi/htpasswd
        target: /data/auth
    command: run -P /data/auth/.htpasswd -a update,download,list /data/packages -v
    ports:
      - "8081:8080"
